# SPDX-FileCopyrightText: 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

# Accepted licesnes by default
accepted = ["Apache-2.0", "MIT"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
  "i686-unknown-linux-gnu",
  "i686-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-gnu",
  "i686-pc-windows-gnu",
]

# Do not ignore any dependencies
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false

# Try to resolve any time clearlydefined.io marks something as NOASSERTION
filter-noassertion = true

# Specify the license from the github page:
# BSD 3-Clause: https://github.com/phsym/prettytable-rs/blob/master/LICENSE.txt
[prettytable-rs]
accepted = ["BSD-3-Clause"]

# Specify the license for `adler32`
# Zlib: https://github.com/remram44/adler32-rs/blob/master/LICENSE
[adler32]
accepted = ["Zlib"]

# Specify the triple license for `encoding-rs`
# MIT: https://github.com/hsivonen/encoding_rs/blob/master/LICENSE-MIT
# Apache-2.0: https://github.com/hsivonen/encoding_rs/blob/master/LICENSE-APACHE
# BSD-3-Clause: https://github.com/hsivonen/encoding_rs/blob/master/LICENSE-WHATWG
[encoding_rs]
accepted = ["BSD-3-Clause"]

# Specify the license for `inotify`
# ISC: https://github.com/hannobraun/inotify-rs/blob/main/LICENSE
[inotify]
accepted = ["ISC"]

# Specify the license for `inotify-sys`
# ISC: https://github.com/hannobraun/inotify-sys/blob/master/LICENSE
[inotify-sys]
accepted = ["ISC"]

# Specify the license for `mdbook`
# MPL-2.0: https://github.com/rust-lang/mdBook/blob/master/LICENSE
[mdbook]
accepted = ["MPL-2.0"]

# Specify the license for `notify`
# CC0-1.0: https://github.com/notify-rs/notify/blob/main/notify/LICENSE-CC0
[notify]
accepted = ["CC0-1.0"]

# Specify the triple license for `unicode-ident`
# MIT: https://github.com/dtolnay/unicode-ident/LICENSE-MIT
# Apache-2.0: https://github.com/dtolnay/unicode-ident/LICENSE-APACHE
# Unicode-DFS-2016: https://github.com/dtolnay/unicode-ident/LICENSE-UNICODE
[unicode-ident]
accepted = ["Unicode-3.0"]

[rustix.clarify]
license = "Apache-2.0 OR (Apache-2.0 WITH LLVM-exception) OR MIT"

[[rustix.clarify.git]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2" # pragma: allowlist secret

[[rustix.clarify.git]]
path = "LICENSE-Apache-2.0_WITH_LLVM-exception"
license = "Apache-2.0 WITH LLVM-exception"
checksum = "268872b9816f90fd8e85db5a28d33f8150ebb8dd016653fb39ef1f94f2686bc5" # pragma: allowlist secret


[[rustix.clarify.git]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "23f18e03dc49df91622fe2a76176497404e46ced8a715d9d2b67a7446571cca3" # pragma: allowlist secret


[linux-raw-sys.clarify]
license = "Apache-2.0 OR (Apache-2.0 WITH LLVM-exception) OR MIT"

[[linux-raw-sys.clarify.git]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2" # pragma: allowlist secret


[[linux-raw-sys.clarify.git]]
path = "LICENSE-Apache-2.0_WITH_LLVM-exception"
license = "Apache-2.0 WITH LLVM-exception"
checksum = "268872b9816f90fd8e85db5a28d33f8150ebb8dd016653fb39ef1f94f2686bc5" # pragma: allowlist secret


[[linux-raw-sys.clarify.git]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "23f18e03dc49df91622fe2a76176497404e46ced8a715d9d2b67a7446571cca3" # pragma: allowlist secret
